<?xml version="1.0" encoding="utf-8"?><Database Name="JSONdb" Class="JSONFileDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=JSONdb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="JSONdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.JSON_Table" Member="JSON_Table">
    <Type Name="JSON_Table">
      <Column Name="JSONID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JSON" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>