#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JSONdb")]
	public partial class JSONFileDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertJSON_Table(JSON_Table instance);
    partial void UpdateJSON_Table(JSON_Table instance);
    partial void DeleteJSON_Table(JSON_Table instance);
    #endregion
		
		public JSONFileDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JSONdbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JSONFileDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JSONFileDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JSONFileDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JSONFileDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<JSON_Table> JSON_Table
		{
			get
			{
				return this.GetTable<JSON_Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JSON_Table")]
	public partial class JSON_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JSONID;
		
		private string _JSON;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJSONIDChanging(int value);
    partial void OnJSONIDChanged();
    partial void OnJSONChanging(string value);
    partial void OnJSONChanged();
    #endregion
		
		public JSON_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JSONID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int JSONID
		{
			get
			{
				return this._JSONID;
			}
			set
			{
				if ((this._JSONID != value))
				{
					this.OnJSONIDChanging(value);
					this.SendPropertyChanging();
					this._JSONID = value;
					this.SendPropertyChanged("JSONID");
					this.OnJSONIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JSON", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string JSON
		{
			get
			{
				return this._JSON;
			}
			set
			{
				if ((this._JSON != value))
				{
					this.OnJSONChanging(value);
					this.SendPropertyChanging();
					this._JSON = value;
					this.SendPropertyChanged("JSON");
					this.OnJSONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
